POST http://localhost:3500/noyna HTTP/1.1
content-type: application/json

{
    "name": "nayna"
}


###
POST http://localhost:3500/interpolation HTTP/1.1
content-type: application/json

{
    "name": 100,
    "interval": 20
}

