POST http://localhost:5400/bds/noyna HTTP/1.1
content-type: application/json

{
    "name": "noyna"
}


###
POST https://geodev.fun/bds/interpolation HTTP/1.1
content-type: application/json

{
    "dayName": "sunday",
    "timeStart": "15",
    "timeEnd": "16"
}


###
GET https://4f6c-202-28-251-51.ngrok-free.app/sss/api/sendmessage/test กกกกก