POST http://localhost:5400/noyna HTTP/1.1
content-type: application/json

{
    "name": "noyna"
}


###
POST http://localhost:5400/interpolation HTTP/1.1
content-type: application/json

{
    "name": "savg",
    "interval": 20
}

