version: '3.3'
services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      # - POSTGRES_DB=geodb
    ports:
      - 5434:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d

  nodejs:
    image: node
    working_dir: /app
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app
    ports:
      - 3200:3000
    command: sh -c "npm i && npm i -g nodemon && nodemon server.js"

  gdal:
    image: osgeo/gdal:ubuntu-small-3.6.3
    container_name: gdal
    working_dir: /app
    depends_on:
      - postgis
    volumes:
      - ./gdal:/app
    ports:
      - "5400:5400"
    command: |
      sh -c "
      apt-get update &&
      apt-get install -y python3 python3-pip gdal-bin python3-gdal &&
      pip3 install Flask &&
      cd /app &&
      python3 app.py
      "
