version: '3.3'
services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=geodb
    ports:
      - 5434:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d

  nodejs:
    image: node
    working_dir: /app
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app
    ports:
      - 3200:3000
    command: bash -c "npm i && npm i -g nodemon && nodemon server.js"

  python:
    build:
      context: ./python/
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    ports:
      - '5100:5000'
